export { default as storage } from './storage';
export { default as saveFile } from './saveFile';
export { default as getQuery } from './getQuery';
export { default as deepClone } from './deepClone';
export { default as hasData } from './hasData';
export { default as value2label } from './value2label';
export { default as getNumByDelete } from './getNumByDelete';
export { default as debounce } from './debounce';
export { default as throttle } from './throttle';
export * from './typeOf';
export * from './formatDate';
export * from './thousands';
